# -*-coding:utf-8 -*-
'''
Created on 2015年7月1日

@author: gaoweiwei
'''
import os,sys
_WORKSPACE = os.getcwd()[0:os.getcwd().find('AutoSMS')+8]
_APIPATH =_WORKSPACE+'\\sms_data\\api\\'
_CASEPATH=_WORKSPACE+'\\sms_data\\case\\'

sms_api={
         'HandShake':{
                      'apiname':'HandShake',
                      'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-sms/sms/HandShake.json',
                      'apimethod':'GET',
                      'apiprams':['taskDesc','operator','src','expireTime'],
                      'apipath':_APIPATH+'HandShake.api.xml',
                      'apicase':_CASEPATH+'HandShake.case.csv',
          },
         'phone':{
                      'apiname':'phone',
                      'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-sms/sms/phone.json',
                      'apimethod':'POST',
                      'apiprams':['taskId','dest','temptId','params','startTime','src','operator','expiretime',
                                  'tokenExpireTime','callbackParams','callbackUrl','needToken'],
                      'apipath':_APIPATH+'phone.api.xml',
                      'apicase':_CASEPATH+'phone.case.csv',
                  },
         'schedulePhone':{
                          'apiname':'schedulePhone',
                          'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588//mc-sms/sms/schedulePhone.json',
                          'apimethod':'POST',
                          'apiprams':['taskId','dest','temptId','params','startTime','src','operator','expireTime'],
                          'apipath':_APIPATH+'schedulePhone.api.xml',
                          'apicase':_CASEPATH+'schedulePhone.case.csv',
                          },
         'upLinkCallback':{
                           'apiname':'upLinkCallback',
                           'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-sms/sms/upLinkCallback.json',
                           'apimethod':'POST',
                           'apiprams':['phone','msgContent','msgId','userName','password','signature'],
                           'apipath':_APIPATH+'upLinkCallback.api.xml',
                           'apicase':_CASEPATH+'upLinkCallback.case.csv',                  
                           },
         
         #########################push############################################
         'register':{
                   'apiname':'register',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-web/register.html',
                   'apimethod':'GET',
                   'apiprams':['product','appid','pushuid','channelid','devicetoken','platform','cuid','userid',
                               'cityid','version','channel','pushremind','status','cause','pushenable'],
                   'apipath':_APIPATH+'register.api.xml',
                   'apicase':_CASEPATH+'register.case.csv',
                   },
         'uninstall':{
                   'apiname':'uninstall',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-web/uninstall.html',
                   'apimethod':'GET',
                   'apiprams':['prod','cuid'],
                   'apipath':_APIPATH+'uninstall.api.xml',
                   'apicase':_CASEPATH+'uninstall.case.csv',
                   },
         'single':{
                   'apiname':'single',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-web/push/single.html',
                   'apimethod':'GET',
                   'apiprams':['prod','utype','pid','uid','title','content','type','info','src','at','et','operator'],
                   'apipath':_APIPATH+'single.api.xml',
                   'apicase':_CASEPATH+'single.case.csv',
                   },
         'groupid':{
                   'apiname':'groupid',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-web/push/groupid.html',
                   'apimethod':'GET',
                   'apiprams':['desc','src','prod'],
                   'apipath':_APIPATH+'groupid.api.xml',
                   'apicase':_CASEPATH+'groupid.case.csv',
                   },
         'push_handshake':{
                   'apiname':'push_handshake',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-web/push/HandShake.html',
                   'apimethod':'GET',
                   'apiprams':['desc','src','groupid','prod','taskflag','expiretime'],
                   'apipath':_APIPATH+'push_handshake.api.xml',
                   'apicase':_CASEPATH+'push_handshake.case.csv',
                   },
         'users':{
                   'apiname':'users',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-web/push/users.html',
                   'apimethod':'POST',
                   'apiprams':['utype','src','groupid','prod','uids','type','title','content','info','at','et','operator'],
                   'apipath':_APIPATH+'users.api.xml',
                   'apicase':_CASEPATH+'users.case.csv',
                   },
         'condition':{
                   'apiname':'condition',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-web/push/condition.html',
                   'apimethod':'GET',
                   'apiprams':['prod','cityid','platform','title','content','type','info','src','at','et','operator'],
                   'apipath':_APIPATH+'condition.api.xml',
                   'apicase':_CASEPATH+'condition.case.csv',
                   },
         ###########################stat########################
         'statistics':{
                   'apiname':'statistics',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-web/statistics.html',
                   'apimethod':'GET',
                   'apiprams':['gid','cuid','pass_uid','tn','location','appid','net','sheight','client_ip','timestamp',
                               'log_id','os','pid','msg','terminal_type','cityid','product','v','swidth','device','uuid','ua','from'],
                   'apipath':_APIPATH+'statistics.api.xml',
                   'apicase':_CASEPATH+'statistics.case.csv',
                   },
         ################################notice##################################
         'list':{
                   'apiname':'list',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-notice/list.html',
                   'apimethod':'GET',
                   'apiprams':['userid','prodid'],
                   'apipath':_APIPATH+'list.api.xml',
                   'apicase':_CASEPATH+'list.case.csv',
                   },
         'tab':{
                   'apiname':'tab',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-notice/tab.html',
                   'apimethod':'GET',
                   'apiprams':['userid','prodid'],
                   'apipath':_APIPATH+'tab.api.xml',
                   'apicase':_CASEPATH+'tab.case.csv',
                   },
         'latelytime':{
                   'apiname':'latelytime',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-notice/latelytime.html',
                   'apimethod':'GET',
                   'apiprams':['userid','prodid'],
                   'apipath':_APIPATH+'latelytime.api.xml',
                   'apicase':_CASEPATH+'latelytime.case.csv',
                   },
         'unreadednum':{
                   'apiname':'unreadednum',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-notice/unreadednum.html',
                   'apimethod':'GET',
                   'apiprams':['userid','prodid'],
                   'apipath':_APIPATH+'unreadednum.api.xml',
                   'apicase':_CASEPATH+'unreadednum.case.csv',
                   },
         'update':{
                   'apiname':'update',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-notice/update.html',
                   'apimethod':'GET',
                   'apiprams':['userid','prodid','msgids'],
                   'apipath':_APIPATH+'update.api.xml',
                   'apicase':_CASEPATH+'update.case.csv',
                   },
         'delete':{
                   'apiname':'delete',
                   'apiurl':'http://cp01-tuangou-qa02.cp01.baidu.com:8588/mc-notice/delete.html',
                   'apimethod':'GET',
                   'apiprams':['userid','prodid','msgids'],
                   'apipath':_APIPATH+'delete.api.xml',
                   'apicase':_CASEPATH+'delete.case.csv',
                   },
         
         
         }
sms_db={
              'host':'10.95.44.36',
              'port':8509,
              'user':'msgcenter',
              'passwd':'123456',
              'db':'msgcenter',
        }